config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :ephemera_projects do
    resources :ephemera_fields
  end
  get '/ephemera_projects/:ephemera_project_id/box' => 'hyrax/ephemera_boxes#new', as: 'ephemera_project_add_box'

  mount Grocer::Engine => '/'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount BrowseEverything::Engine => '/browse'

  mount Blacklight::Engine => '/'
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  resource :catalog, only: [:index], controller: 'catalog' do
    concerns :searchable
  end
  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:passwords, :registration]
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'users/auth/cas', to: 'users/omniauth_authorize#passthru', defaults: { provider: :cas }, as: "new_user_session"
  end
  mount Hydra::RoleManagement::Engine => '/'

  resources :welcome, only: 'index'
  root to: 'welcome#index'
  # Add URL options
  default_url_options Rails.application.config.action_mailer.default_url_options

  # Collections have to go before CC routes, to add index_manifest.
  scope module: 'hyrax' do
    resources :collections do
      member do
        get :manifest, defaults: { format: :json }
      end
    end
  end
  mount Hyrax::Engine, at: '/'
  curation_concerns_basic_routes
  curation_concerns_embargo_management

  mount GeoWorks::Engine => '/'
  get "/iiif/collections", defaults: { format: :json }, controller: 'hyrax/collections', action: :index_manifest
  get "/iiif/lookup/:prefix/:naan/:arkid", controller: 'catalog', action: :lookup_manifest, as: :lookup_manifest

  namespace :hyrax, path: :concern do
    resources :parent, only: [] do
      [:multi_volume_works, :scanned_resources, :ephemera_folders, :map_sets].each do |type|
        resources type, only: [] do
          member do
            get :file_manager
            get :structure
          end
          collection do
            resources :templates, defaults: { class_type: type.to_s.classify }, as: :"parent_#{type.to_s.singularize}_templates"
          end
        end
      end
    end
    resources :multi_volume_works, only: [] do
      member do
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        get :structure
        post :structure, action: :save_structure
      end
    end
    resources :scanned_resources, only: [] do
      member do
        get "/pdf/:pdf_quality", action: :pdf, as: :pdf
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        post :bulk_download
      end
      collection do
        resources :templates, defaults: { class_type: "ScannedResource" }, as: :scanned_resource_templates
      end
    end
    resources :ephemera_folders, only: [] do
      member do
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
      end
      collection do
        resources :templates, defaults: { class_type: "EphemeraFolder" }, as: :ephemera_folder_templates
      end
    end
    resources :image_works, only: [] do
      member do
        get :manifest, defaults: { format: :json }
      end
    end
    resources :map_sets, only: [] do
      member do
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        get :geoblacklight, defaults: { format: :json }
      end
    end
    resources :file_sets, only: [] do
      member do
        post :derivatives
      end
    end
  end

  namespace :hyrax, path: :concern do
    resources :file_sets, only: [], path: 'container/:parent_id/file_sets', as: 'member_file_set' do
      member do
        get :text, defaults: { format: :json }
      end
    end
    resources :confirm, only: [] do
      member do
        get :state
        post :copy_state
        get :visibility
        post :copy_visibility
      end
    end
  end

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Dynamic robots.txt
  get '/robots.:format' => 'pages#robots'

  mount Qa::Engine => '/authorities'

  resources :vocabularies
  resources :vocabulary_terms
  get '/vocabularies/:vocabulary_id/add_term' => 'vocabulary_terms#new', as: 'vocabulary_add_term'
  get '/vocabularies/:parent_id/add_category' => 'vocabularies#new', as: 'vocabulary_add_category'
  resources :auth_tokens
  resources :templates, only: [:index], controller: "hyrax/templates"
end

app/models/ephemera_project.rb
# frozen_string_literal: true
class EphemeraProject < ApplicationRecord
  has_many :ephemera_fields

  validates :name, presence: true
end

app/controllers/ephemera_projects_controller.rb
# frozen_string_literal: true
class EphemeraProjectsController < ApplicationController
  before_action :set_ephemera_project, only: [:show, :edit, :update, :destroy]
  authorize_resource only: [:new, :edit, :create, :update, :destroy]

  # GET /ephemera_projects
  # GET /ephemera_projects.json
  def index
    @ephemera_projects = EphemeraProject.all
  end

  # GET /ephemera_projects/1
  # GET /ephemera_projects/1.json
  def show
    @templates = Template.where(template_class: "EphemeraFolder").select { |x| x.params["ephemera_project_id"] == @ephemera_project.id.to_s }
  end

  # GET /ephemera_projects/new
  def new
    @ephemera_project = EphemeraProject.new
  end

  # GET /ephemera_projects/1/edit
  def edit; end

  # POST /ephemera_projects
  # POST /ephemera_projects.json
  def create
    @ephemera_project = EphemeraProject.new(ephemera_project_params)

    respond_to do |format|
      if @ephemera_project.save
        format.html { redirect_to @ephemera_project, notice: 'Ephemera project was successfully created.' }
        format.json { render :show, status: :created, location: @ephemera_project }
      else
        format.html { render :new }
        format.json { render json: @ephemera_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ephemera_projects/1
  # PATCH/PUT /ephemera_projects/1.json
  def update
    respond_to do |format|
      if @ephemera_project.update(ephemera_project_params)
        format.html { redirect_to @ephemera_project, notice: 'Ephemera project was successfully updated.' }
        format.json { render :show, status: :ok, location: @ephemera_project }
      else
        format.html { render :edit }
        format.json { render json: @ephemera_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ephemera_projects/1
  # DELETE /ephemera_projects/1.json
  def destroy
    @ephemera_project.destroy
    respond_to do |format|
      format.html { redirect_to ephemera_projects_url, notice: 'Ephemera project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_ephemera_project
      @ephemera_project = EphemeraProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ephemera_project_params
      params.require(:ephemera_project).permit(:name)
    end
end

app/views/ephemera_projects/_form.html.erb
<%= form_for(ephemera_project) do |f| %>
  <% if ephemera_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ephemera_project.errors.count, "error") %> prohibited this ephemera_project from being saved:</h2>

      <ul>
      <% ephemera_project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit(class: 'btn btn-primary') %>

    <% if params[:action] == "new" %>
      <%= link_to 'Cancel', ephemera_projects_path, class: 'btn btn-default' %>
    <% else %>
      <%= link_to 'Cancel', @ephemera_project, class: 'btn btn-default' %>
      <%= link_to 'Delete This Project', @ephemera_project, class: 'btn btn-danger pull-right', data: { confirm: "Delete this Project?" }, method: :delete %>
    <% end %>
  </div>
<% end %>

app/views/ephemera_projects/edit.html.erb
<h1>Editing Ephemera Project</h1>

<%= render 'form', ephemera_project: @ephemera_project %>

app/views/ephemera_projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ephemera Projects</h1>

<ul>
  <% @ephemera_projects.order(:name).each do |ephemera_project| %>
      <li><%= link_to ephemera_project.name, ephemera_project %></li>
  <% end %>
</ul>

<br>

<% if can?(:create, EphemeraProject) %>
  <%= link_to 'New Ephemera Project', new_ephemera_project_path, class: 'btn btn-primary' %>
<% end %>

app/views/ephemera_projects/new.html.erb
<h1>New Ephemera Project</h1>

<%= render 'form', ephemera_project: @ephemera_project %>

app/views/ephemera_projects/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @ephemera_project.name %></h1>
<% if can?(:modify, @ephemera_project) %>
  <%= link_to 'Edit', edit_ephemera_project_path(@ephemera_project), class: 'btn btn-primary' %>
<% end %>
<%= link_to 'All Ephemera Projects', ephemera_projects_path, class: 'btn btn-default' %>

<br/><br/>

<h2>Boxes</h2>

<ul>
  <% EphemeraBox.where(ephemera_project_id_ssim: "#{@ephemera_project.id}").each do |box| %>
    <li><%= link_to "Box #{box.box_number.first}", box %></li>
  <% end %>
</ul>
<% if can?(:create, EphemeraBox) %>
  <%= link_to 'Add Box', ephemera_project_add_box_path(@ephemera_project), class: 'btn btn-primary' %>
<% end %>

<br/><br/>

<h2>Controlled Fields</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Vocabulary</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @ephemera_project.ephemera_fields.order(:name).each do |ephemera_field| %>
      <tr>
        <td><%= ephemera_field.name %></td>
        <td><%= link_to ephemera_field.vocabulary.label, ephemera_field.vocabulary %></td>
        <% if can?(:modify, ephemera_field) %>
          <td><%= link_to 'Edit', edit_ephemera_project_ephemera_field_path(@ephemera_project, ephemera_field) %></td>
        <% end %>
        <% if can?(:delete, ephemera_field) %>
          <td><%= link_to 'Destroy', ephemera_project_ephemera_field_path(@ephemera_project, ephemera_field), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can?(:create, EphemeraField) %>
  <%= link_to 'Add Field', new_ephemera_project_ephemera_field_path(@ephemera_project), class: 'btn btn-primary' %>
<% end %>

<h2>Templates</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Template Label</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.template_label %></td>
        <td>
          <%= link_to "Delete", polymorphic_path([main_app, :hyrax, template.template_class.underscore, template]), class: 'btn btn-danger', method: :delete, data: { confirm: "Really delete #{template.template_label}?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>