config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :ephemera_projects do
    resources :ephemera_fields
  end
  get '/ephemera_projects/:ephemera_project_id/box' => 'hyrax/ephemera_boxes#new', as: 'ephemera_project_add_box'

  mount Grocer::Engine => '/'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount BrowseEverything::Engine => '/browse'

  mount Blacklight::Engine => '/'
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  resource :catalog, only: [:index], controller: 'catalog' do
    concerns :searchable
  end
  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:passwords, :registration]
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'users/auth/cas', to: 'users/omniauth_authorize#passthru', defaults: { provider: :cas }, as: "new_user_session"
  end
  mount Hydra::RoleManagement::Engine => '/'

  resources :welcome, only: 'index'
  root to: 'welcome#index'
  # Add URL options
  default_url_options Rails.application.config.action_mailer.default_url_options

  # Collections have to go before CC routes, to add index_manifest.
  scope module: 'hyrax' do
    resources :collections do
      member do
        get :manifest, defaults: { format: :json }
      end
    end
  end
  mount Hyrax::Engine, at: '/'
  curation_concerns_basic_routes
  curation_concerns_embargo_management

  mount GeoWorks::Engine => '/'
  get "/iiif/collections", defaults: { format: :json }, controller: 'hyrax/collections', action: :index_manifest
  get "/iiif/lookup/:prefix/:naan/:arkid", controller: 'catalog', action: :lookup_manifest, as: :lookup_manifest

  namespace :hyrax, path: :concern do
    resources :parent, only: [] do
      [:multi_volume_works, :scanned_resources, :ephemera_folders, :map_sets].each do |type|
        resources type, only: [] do
          member do
            get :file_manager
            get :structure
          end
          collection do
            resources :templates, defaults: { class_type: type.to_s.classify }, as: :"parent_#{type.to_s.singularize}_templates"
          end
        end
      end
    end
    resources :multi_volume_works, only: [] do
      member do
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        get :structure
        post :structure, action: :save_structure
      end
    end
    resources :scanned_resources, only: [] do
      member do
        get "/pdf/:pdf_quality", action: :pdf, as: :pdf
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        post :bulk_download
      end
      collection do
        resources :templates, defaults: { class_type: "ScannedResource" }, as: :scanned_resource_templates
      end
    end
    resources :ephemera_folders, only: [] do
      member do
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
      end
      collection do
        resources :templates, defaults: { class_type: "EphemeraFolder" }, as: :ephemera_folder_templates
      end
    end
    resources :image_works, only: [] do
      member do
        get :manifest, defaults: { format: :json }
      end
    end
    resources :map_sets, only: [] do
      member do
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        get :geoblacklight, defaults: { format: :json }
      end
    end
    resources :file_sets, only: [] do
      member do
        post :derivatives
      end
    end
  end

  namespace :hyrax, path: :concern do
    resources :file_sets, only: [], path: 'container/:parent_id/file_sets', as: 'member_file_set' do
      member do
        get :text, defaults: { format: :json }
      end
    end
    resources :confirm, only: [] do
      member do
        get :state
        post :copy_state
        get :visibility
        post :copy_visibility
      end
    end
  end

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Dynamic robots.txt
  get '/robots.:format' => 'pages#robots'

  mount Qa::Engine => '/authorities'

  resources :vocabularies
  resources :vocabulary_terms
  get '/vocabularies/:vocabulary_id/add_term' => 'vocabulary_terms#new', as: 'vocabulary_add_term'
  get '/vocabularies/:parent_id/add_category' => 'vocabularies#new', as: 'vocabulary_add_category'
  resources :auth_tokens
  resources :templates, only: [:index], controller: "hyrax/templates"
end

app/controllers/concerns/hyrax/collection_manifest.rb
# frozen_string_literal: true
module Hyrax::CollectionManifest
  extend ActiveSupport::Concern

  included do
    def index_manifest
      respond_to do |f|
        f.json do
          render json: all_manifests_builder
        end
      end
    rescue CanCan::AccessDenied => access_err
      deny_access(access_err)
    rescue ManifestBuilder::ManifestEmptyError
      render json: {}, status: :not_found
    rescue => err
      render json: { message: err.message }, status: :internal_server_error
    end

    def deny_access(exception)
      if exception.action == :manifest && !current_user
        render json: {}, status: :unauthorized
      elsif !current_user
        session['user_return_to'] = request.url
        redirect_to login_url, alert: exception.message
      else
        super
      end
    end
  end

  private

    def presenter
      @presenter ||=
        begin
          _, document_list = search_results(params)
          curation_concern = document_list.first
          raise CanCan::AccessDenied.new(nil, params[:action].to_sym) unless curation_concern
          @presenter = show_presenter.new(curation_concern, current_ability)
        end
    end

    ##
    # Retrieve the IIIF Manifest for a given Work
    # @return IIIF::Presentation::Manifest
    def all_manifests_builder
      AllCollectionsManifestBuilder.new(nil, ability: current_ability, ssl: request.ssl?).to_json
    end

    def login_url
      main_app.user_cas_omniauth_authorize_url
    end
end

app/controllers/concerns/hyrax/geo_events_behavior.rb
# frozen_string_literal: true
module Hyrax
  module GeoEventsBehavior
    extend ActiveSupport::Concern

    def destroy
      geo_works_events_generator.record_deleted(geo_work)
      super
    end

    def after_update_response
      super
      return unless curation_concern.workflow_state == 'complete'
      geo_works_events_generator.record_updated(geo_work)
    end

    def geo_works_events_generator
      @geo_works_events_generator ||= GeoWorks::EventsGenerator.new
    end

    def geo_work
      doc = ::SolrDocument.new(curation_concern.to_solr)
      show_presenter.new(doc, current_ability, request)
    end
  end
end

app/controllers/concerns/hyrax/geo_file_set_events_behavior.rb
# frozen_string_literal: true
module Hyrax
  module GeoFileSetEventsBehavior
    extend ActiveSupport::Concern

    def create
      super
      return unless curation_concern.parent.workflow_state == 'complete'
      geo_works_events_generator.record_updated(geo_work)
    end

    def destroy
      parent_workflow_state = curation_concern.parent.workflow_state
      parent_work = geo_work
      super
      return unless parent_workflow_state == 'complete'
      geo_works_events_generator.record_updated(parent_work)
    end

    def geo_works_events_generator
      @geo_works_events_generator ||= GeoWorks::EventsGenerator.new
    end

    def geo_work
      doc = ::SolrDocument.new(curation_concern.parent.to_solr)
      geo_work_show_presenter_class.new(doc, current_ability, request)
    end

    def geo_work_show_presenter_class
      ::DynamicShowPresenter.new
    end
  end
end

app/controllers/concerns/hyrax/geo_messenger_behavior.rb
module Hyrax
  module GeoMessengerBehavior
    extend ActiveSupport::Concern

    def destroy
      geo_works_messenger.record_deleted(geo_work)
      super
    end

    def after_update_response
      super
      return unless curation_concern.workflow_state == 'complete'
      geo_works_messenger.record_updated(geo_work)
    end

    def geo_works_messenger
      @geo_works_messenger ||= GeoWorks::Messaging.messenger
    end

    def geo_work
      doc = ::SolrDocument.new(curation_concern.to_solr)
      show_presenter.new(doc, current_ability, request)
    end
  end
end

app/controllers/concerns/hyrax/manifest.rb
# frozen_string_literal: true
module Hyrax::Manifest
  extend ActiveSupport::Concern

  included do
    def manifest
      respond_to do |f|
        f.json do
          render json: manifest_builder
        end
      end
    rescue CanCan::AccessDenied => access_err
      deny_access(access_err)
    rescue ManifestBuilder::ManifestEmptyError
      render json: {}, status: :not_found
    rescue => err
      render json: { message: err.message }, status: :internal_server_error
    end

    def deny_access(exception)
      if exception.action == :manifest && !current_user
        render json: {}, status: :unauthorized
      elsif !current_user
        session['user_return_to'] = request.url
        redirect_to login_url, alert: exception.message
      else
        super
      end
    end
  end

  private

    def presenter
      @presenter ||=
        begin
          _, document_list = search_results(params)
          curation_concern = document_list.first
          raise CanCan::AccessDenied.new(nil, params[:action].to_sym) unless curation_concern
          @presenter = show_presenter.new(curation_concern, current_ability)
        end
    end

    ##
    # Retrieve the IIIF Manifest for a given Work
    # @return IIIF::Presentation::Manifest
    def manifest_builder
      Rails.cache.fetch("manifest/#{presenter.id}/#{ResourceIdentifier.new(presenter.id)}") do
        PolymorphicManifestBuilder.new(presenter, ssl: request.ssl?).to_json
      end
    end

    def login_url
      main_app.user_cas_omniauth_authorize_url
    end
end

app/controllers/concerns/hyrax/member_management.rb
# frozen_string_literal: true
module Hyrax::MemberManagement
  extend ActiveSupport::Concern

  included do
    def structure
      parent_presenter
      @members = presenter.member_presenters
      @logical_order = presenter.logical_order_object
    end

    def save_structure
      begin
        curation_concern.logical_order.destroy(eradicate: true)
      rescue Ldp::Gone
        ActiveFedora::Base.eradicate("#{curation_concern.id}/logical_order")
      end
      curation_concern.reload
      curation_concern.logical_order.order = { "label": params.to_unsafe_h["label"], "nodes": params.to_unsafe_h["nodes"] }
      curation_concern.save!
      head 200
    rescue StandardError => e
      Rails.logger.warn "Error: #{e.message}"
    end
  end
end

app/controllers/concerns/hyrax/remote_metadata.rb
# frozen_string_literal: true
module Hyrax::RemoteMetadata
  extend ActiveSupport::Concern

  private

    def decorator
      if wants_to_update_remote_metadata?
        CompositeDecorator.new(UpdatesMetadata, super)
      else
        super
      end
    end

    def wants_to_update_remote_metadata?
      params[:action] == "create" || params[:refresh_remote_metadata]
    end
end

app/controllers/concerns/hyrax/update_ocr.rb
# frozen_string_literal: true
module Hyrax
  module UpdateOCR
    extend ActiveSupport::Concern
    def decorator
      ::UpdatesOCR
    end
  end
end

app/controllers/hyrax/batch_uploads_controller.rb
# frozen_string_literal: true
class Hyrax::BatchUploadsController < ApplicationController
  include Hyrax::BatchUploadsControllerBehavior

  # Gives the class of the form.
  class BatchUploadFormService < Hyrax::WorkFormService
    def self.form_class(_ = nil)
      ::Hyrax::BatchUploadForm
    end
  end

  self.work_form_service = BatchUploadFormService

  def create
    if params[:uploaded_files]
      super
    else
      flash[:error] = 'Please upload a file.'
      redirect_back fallback_location: root_path
    end
  end

  protected

    def create_update_job(klass)
      BatchCreateJob.perform_later(current_user,
                                   params[:uploaded_files],
                                   attributes_for_actor.to_h.merge!(model: klass))
    end

    def redirect_after_update
      redirect_to main_app.search_catalog_path
    end
end

app/controllers/hyrax/collections_controller.rb
# frozen_string_literal: true
class Hyrax::CollectionsController < ApplicationController
  include Hyrax::Manifest
  include Hyrax::CollectionManifest
  include Hyrax::CollectionsControllerBehavior
  skip_load_and_authorize_resource only: :index_manifest
  skip_before_action :authenticate_user!, only: [:index_manifest, :manifest]
  self.presenter_class = CollectionShowPresenter
  self.form_class = CollectionEditForm

  def current_ability
    ::Ability.new(current_user, auth_token: params[:auth_token])
  end
end

app/controllers/hyrax/confirm_controller.rb
# frozen_string_literal: true
# see Hyrax::PermissionsControllerBehavior
class Hyrax::ConfirmController < ApplicationController
  helper_method :curation_concern

  def state
    # intentional noop to display default view
  end

  def copy_state
    authorize! :edit, curation_concern
    CopyStateJob.perform_later(curation_concern)
    flash_message = 'Updating state of attached volumes. This may take a few minutes.'
    redirect_to [main_app, curation_concern], notice: flash_message
  end

  def visibility
    # intentional noop to display default view
  end

  def copy_visibility
    authorize! :edit, curation_concern
    CopyVisibilityJob.perform_later(curation_concern)
    flash_message = 'Updating visibility of attached volumes. This may take a few minutes.'
    redirect_to [main_app, curation_concern], notice: flash_message
  end

  def curation_concern
    @curation_concern ||= ActiveFedora::Base.find(params[:id])
  end
end

app/controllers/hyrax/curation_concerns_controller.rb
class Hyrax::HyraxController < ApplicationController
  include Hyrax::CurationConcernController
  include Hyrax::Manifest
  include Hyrax::MemberManagement
  include Hyrax::UpdateOCR
  include Hyrax::RemoteMetadata

  def destroy
    messenger.record_deleted(curation_concern)
    super
  end

  def file_manager
    parent_presenter
    super
  end

  def browse_everything_files
    upload_set_id = ActiveFedora::Noid::Service.new.mint
    CompositePendingUpload.create(selected_files_params, curation_concern.id, upload_set_id)
    BrowseEverythingIngestJob.perform_later(curation_concern.id, upload_set_id, current_user, selected_files_params)
    redirect_to ::ContextualPath.new(curation_concern, parent_presenter).file_manager
  end

  def after_create_response
    send_record_created
    super
  end

  def send_record_created
    messenger.record_created(curation_concern)
  end

  private

    def search_builder_class
      ::WorkSearchBuilder
    end

    def messenger
      @messenger ||= ManifestEventGenerator.new(Plum.messaging_client)
    end

    def curation_concern
      @decorated_concern ||=
        begin
          @curation_concern = decorator.new(@curation_concern)
        end
    end

    def decorator
      CompositeDecorator.new(super, NullDecorator)
    end

    def selected_files_params
      params[:selected_files].to_unsafe_h
    end
end

app/controllers/hyrax/downloads_controller.rb
# frozen_string_literal: true
module Hyrax
  class DownloadsController < ApplicationController
    include Hyrax::DownloadBehavior

    protected

      def authorize_download!
        case params[:file]
        when "gray-pdf"
          authorize! :pdf, asset
        when "color-pdf"
          authorize! :color_pdf, asset
        when "thumbnail"
          authorize_thumbnail(asset)
        else
          authorize! :download, asset
        end
      end

    private

      # Allow all thumnbnail downloads if asset is a geo file set, otherwise authorize as a regular download
      def authorize_thumbnail(asset)
        authorize!(:download, asset) unless asset.respond_to?(:geo_mime_type) && !asset.geo_mime_type.blank?
      end

      def load_file
        file_reference = params[:file]
        return default_file unless file_reference

        file_path = PairtreeDerivativePath.derivative_path_for_reference(asset, file_reference)
        File.exist?(file_path) ? file_path : nil
      end

      def default_file
        File.exist?(asset.local_file) ? asset.local_file : super
      end
  end
end

app/controllers/hyrax/ephemera_boxes_controller.rb
# frozen_string_literal: true
# Generated via
#  `rails generate hyrax:work EphemeraBox`

module Hyrax
  class EphemeraBoxesController < ApplicationController
    # Adds Hyrax behaviors to the controller.
    include Hyrax::WorksControllerBehavior
    include Hyrax::BreadcrumbsForWorks
    self.curation_concern_type = EphemeraBox
    self.show_presenter = EphemeraBoxPresenter

    def show
      super
      @available_templates = Template.where(template_class: "EphemeraFolder").select { |x| x.params["ephemera_project_id"] == @presenter.ephemera_project_id }
    end
  end
end

app/controllers/hyrax/image_works_controller.rb
# frozen_string_literal: true
class Hyrax::ImageWorksController < Hyrax::GeoWorksController
  include GeoWorks::ImageWorksControllerBehavior
  include Hyrax::Manifest
  include Hyrax::RemoteMetadata
  self.curation_concern_type = ImageWork

  def show_presenter
    ImageWorkShowPresenter
  end
end

app/views/hyrax/file_sets/_file_set.html.erb
<tr class="<%= dom_class(file_set) %> attributes">
  <td class="thumbnail">
    <%= render_thumbnail_tag file_set, onerror: default_icon_fallback %>
  </td>
  <td class="attribute filename"><%= link_to(file_set.label, main_app.hyrax_file_set_path(file_set)) %>
    <% if file_set.title && file_set.title != file_set.label %>
      <div class="pagenumber"><%= file_set.title %></div>
    <% end %>
  </td>
  <td class="attribute date_uploaded"><%= file_set.date_uploaded %></td>
  <td class="attribute permission"><%= file_set.permission_badge %></td>
  <td>
    <%= render 'hyrax/file_sets/actions', file_set: file_set %>
  </td>
</tr>

app/views/hyrax/file_sets/_form.html.erb
<%= simple_form_for [main_app, file_set],
                    html: { multipart: true, data: { param_key: file_set.model_name.param_key } } do |f| %>
  <fieldset class="required">
    <span class="control-label">
      <%= label_tag 'file_set[title][]', 'Title',  class: "string optional" %>
    </span>
    <%= text_field_tag 'file_set[title][]', file_set.title.first, class: 'form-control', required: true %>
  </fieldset>

  <fieldset class="required">
    <%= render "permission_form", f: f %>
  </fieldset>

  <div class="row">
    <div class="col-md-12 form-actions">
      <%= f.submit(
        (file_set.persisted? ? "Update Attached File" : %(Attach to #{file_set.parent.human_readable_type})),
        class: 'btn btn-primary'
      ) %>
      <%= link_to 'Cancel', parent_path(file_set.parent), class: 'btn btn-link' %>
    </div>
  </div>
<% end %>

app/views/hyrax/file_sets/_permission_form.html.erb
<% depositor = f.object.depositor %>
<% public_perm = f.object.permissions.map { |perm| perm.access if perm.agent_name == "public"}.compact.first %>
<% public_perm = true if params[:controller] == 'batch' %>
<% registered_perm = f.object.permissions.map { |perm| perm.access if perm.agent_name == "registered"}.compact.first %>

<h2 id="permissions_display"><% if params[:controller] == 'batch' %>Bulk <% end %>Permissions <% if params[:controller] == 'batch' %>
      <small>(applied to all files just uploaded)</small><% end %>
</h2>

<div class="alert alert-info hidden" id="save_perm_note">Permissions are <strong>not</strong> saved until the &quot;Save&quot; button is pressed at the bottom of the page.</div>

<div class="alert alert-warning hidden" role="alert" id="permissions_error">
  <span id="permissions_error_text"></span>
</div>

<%= render 'hyrax/base/form_permission', f: f %>

app/views/hyrax/file_sets/_technical_metadata.html.erb
<table class="table table-striped <%= dom_class(@presenter) %> attributes">
  <caption class="table-heading"><h2>Technical Metadata</h2></caption>
  <thead>
    <tr><th>Attribute Name</th><th>Values</th></tr>
  </thead>
  <tbody>
    <%= @presenter.attribute_to_html(:well_formed) %>
    <%= @presenter.attribute_to_html(:valid) %>
    <%= @presenter.attribute_to_html(:date_uploaded) %>
    <%= @presenter.attribute_to_html(:date_modified) %>
    <%= @presenter.attribute_to_html(:file_size) %>
    <%= @presenter.attribute_to_html(:digest) %>
    <%= @presenter.attribute_to_html(:original_checksum) %>
    <%= @presenter.attribute_to_html(:file_format) %>
    <%= @presenter.attribute_to_html(:profile_name) %>
    <%= @presenter.attribute_to_html(:color_space) %>
    <%= @presenter.attribute_to_html(:height) %>
    <%= @presenter.attribute_to_html(:width) %>
  </tbody>
</table>

app/views/hyrax/file_sets/edit.html.erb
<% provide :page_title, curation_concern_page_title(curation_concern) %>
<% provide :page_header do %>
  <h1 class="lower">Edit <%= curation_concern %></h1>
<% end %>

<div class="row">
  <div class="col-xs-12 col-sm-4">
    <%= media_display curation_concern.to_presenter %>
  </div>
  <div class="col-xs-12 col-sm-8">
    <div>
      <div id="descriptions_display">
        <h2>Descriptions </h2>
        <%= render "form", file_set: curation_concern %>
      </div>
    </div>
  </div><!-- /.col-sm-8 -->
</div><!-- /.row -->

app/views/hyrax/file_sets/show.html.erb
<% provide :page_title, @presenter.page_title %>
<% provide :page_header do %>
  <h1>File Details <small><%= @presenter.title %></small></h1>
<% end %>
<%= media_display @presenter %>
<%= render "attributes", curation_concern: @presenter %>
<%= render "technical_metadata", curation_concern: @presenter %>

  <div class="form-actions">
    <%= link_to "Download this File", hyrax.download_path(@presenter), class: 'btn btn-default' %>
    <%= link_to "Back to #{parent.human_readable_type}", parent_path(parent), class: 'btn btn-default' %>

    <% if can? :edit, @presenter.id %>
      <%= link_to "Edit this File", edit_polymorphic_path([main_app, @presenter]), class: 'btn btn-default'  %>
      <%= link_to( 'Rollback', main_app.versions_hyrax_file_set_path(@presenter),
        { class: 'btn btn-default', title: "Rollback to previous version" }) %>
      <%= link_to( 'Regenerate Derivatives', main_app.derivatives_hyrax_file_set_path(@presenter),
        { method: :post, class: 'btn btn-default', title: "Regenerate derivatives" }) %>
      <%= link_to "Delete This #{@presenter.human_readable_type}", [main_app, @presenter], class: 'btn btn-danger pull-right', data: { confirm: "Delete this #{@presenter.human_readable_type}?" }, method: :delete %>
    <% end %>
  </div>