config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :ephemera_projects do
    resources :ephemera_fields
  end
  get '/ephemera_projects/:ephemera_project_id/box' => 'hyrax/ephemera_boxes#new', as: 'ephemera_project_add_box'

  mount Grocer::Engine => '/'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  mount BrowseEverything::Engine => '/browse'

  mount Blacklight::Engine => '/'
  concern :searchable, Blacklight::Routes::Searchable.new
  concern :exportable, Blacklight::Routes::Exportable.new
  resource :catalog, only: [:index], controller: 'catalog' do
    concerns :searchable
  end
  resources :bookmarks do
    concerns :exportable
    collection do
      delete 'clear'
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:passwords, :registration]
  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'users/auth/cas', to: 'users/omniauth_authorize#passthru', defaults: { provider: :cas }, as: "new_user_session"
  end
  mount Hydra::RoleManagement::Engine => '/'

  resources :welcome, only: 'index'
  root to: 'welcome#index'
  # Add URL options
  default_url_options Rails.application.config.action_mailer.default_url_options

  # Collections have to go before CC routes, to add index_manifest.
  scope module: 'hyrax' do
    resources :collections do
      member do
        get :manifest, defaults: { format: :json }
      end
    end
  end
  mount Hyrax::Engine, at: '/'
  curation_concerns_basic_routes
  curation_concerns_embargo_management

  mount GeoWorks::Engine => '/'
  get "/iiif/collections", defaults: { format: :json }, controller: 'hyrax/collections', action: :index_manifest
  get "/iiif/lookup/:prefix/:naan/:arkid", controller: 'catalog', action: :lookup_manifest, as: :lookup_manifest

  namespace :hyrax, path: :concern do
    resources :parent, only: [] do
      [:multi_volume_works, :scanned_resources, :ephemera_folders, :map_sets].each do |type|
        resources type, only: [] do
          member do
            get :file_manager
            get :structure
          end
          collection do
            resources :templates, defaults: { class_type: type.to_s.classify }, as: :"parent_#{type.to_s.singularize}_templates"
          end
        end
      end
    end
    resources :multi_volume_works, only: [] do
      member do
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        get :structure
        post :structure, action: :save_structure
      end
    end
    resources :scanned_resources, only: [] do
      member do
        get "/pdf/:pdf_quality", action: :pdf, as: :pdf
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        post :bulk_download
      end
      collection do
        resources :templates, defaults: { class_type: "ScannedResource" }, as: :scanned_resource_templates
      end
    end
    resources :ephemera_folders, only: [] do
      member do
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
      end
      collection do
        resources :templates, defaults: { class_type: "EphemeraFolder" }, as: :ephemera_folder_templates
      end
    end
    resources :image_works, only: [] do
      member do
        get :manifest, defaults: { format: :json }
      end
    end
    resources :map_sets, only: [] do
      member do
        get :structure
        post :structure, action: :save_structure
        get :manifest, defaults: { format: :json }
        post :browse_everything_files
        get :geoblacklight, defaults: { format: :json }
      end
    end
    resources :file_sets, only: [] do
      member do
        post :derivatives
      end
    end
  end

  namespace :hyrax, path: :concern do
    resources :file_sets, only: [], path: 'container/:parent_id/file_sets', as: 'member_file_set' do
      member do
        get :text, defaults: { format: :json }
      end
    end
    resources :confirm, only: [] do
      member do
        get :state
        post :copy_state
        get :visibility
        post :copy_visibility
      end
    end
  end

  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Dynamic robots.txt
  get '/robots.:format' => 'pages#robots'

  mount Qa::Engine => '/authorities'

  resources :vocabularies
  resources :vocabulary_terms
  get '/vocabularies/:vocabulary_id/add_term' => 'vocabulary_terms#new', as: 'vocabulary_add_term'
  get '/vocabularies/:parent_id/add_category' => 'vocabularies#new', as: 'vocabulary_add_category'
  resources :auth_tokens
  resources :templates, only: [:index], controller: "hyrax/templates"
end

app/models/auth_token.rb
# frozen_string_literal: true
class AuthToken < ApplicationRecord
  before_create :assign_token
  before_save :clean_groups
  serialize :groups, Array

  private

    def assign_token
      self.token = SecureRandom.hex
    end

    def clean_groups
      self.groups = groups.select(&:present?)
    end
end

app/controllers/auth_tokens_controller.rb
# frozen_string_literal: true
class AuthTokensController < ApplicationController
  before_action :set_auth_token, only: [:show, :edit, :update, :destroy]
  authorize_resource only: [:new, :edit, :create, :update, :destroy]

  # GET /auth_tokens
  # GET /auth_tokens.json
  def index
    @auth_tokens = AuthToken.all
  end

  # GET /auth_tokens/1
  # GET /auth_tokens/1.json
  def show; end

  # GET /auth_tokens/new
  def new
    @auth_token = AuthToken.new
  end

  # GET /auth_tokens/1/edit
  def edit; end

  # POST /auth_tokens
  # POST /auth_tokens.json
  def create
    @auth_token = AuthToken.new(auth_token_params)

    respond_to do |format|
      @auth_token.save
      format.html { redirect_to @auth_token, notice: 'Auth token was successfully created.' }
      format.json { render :show, status: :created, location: @auth_token }
    end
  end

  # PATCH/PUT /auth_tokens/1
  # PATCH/PUT /auth_tokens/1.json
  def update
    respond_to do |format|
      @auth_token.update(auth_token_params)
      format.html { redirect_to @auth_token, notice: 'Auth token was successfully updated.' }
      format.json { render :show, status: :ok, location: @auth_token }
    end
  end

  # DELETE /auth_tokens/1
  # DELETE /auth_tokens/1.json
  def destroy
    @auth_token.destroy
    respond_to do |format|
      format.html { redirect_to auth_tokens_url, notice: 'Auth token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_auth_token
      @auth_token = AuthToken.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auth_token_params
      params.require(:auth_token).permit(:label, groups: [])
    end
end

app/views/auth_tokens/_form.html.erb
<%= simple_form_for(auth_token) do |f| %>
  <% if auth_token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auth_token.errors.count, "error") %> prohibited this auth_token from being saved:</h2>

      <ul>
      <% auth_token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :label %>
  <%= f.input :groups, as: :multi_value %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auth_tokens/edit.html.erb
<h1>Editing Auth Token <%= @auth_token.token %></h1>

<%= render 'form', auth_token: @auth_token %>

<%= link_to 'Show', @auth_token %> |
<%= link_to 'Back', auth_tokens_path %>

app/views/auth_tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auth Tokens</h1>

<table class="table">
  <thead>
    <tr>
      <th>Token</th>
      <th>Label</th>
      <th>Groups</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @auth_tokens.each do |auth_token| %>
      <tr>
        <td><%= auth_token.token %></td>
        <td><%= auth_token.label %></td>
        <td><%= auth_token.groups.to_sentence %></td>
        <td><%= link_to 'Show', auth_token %></td>
        <td><%= link_to 'Edit', edit_auth_token_path(auth_token) %></td>
        <td><%= link_to 'Destroy', auth_token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auth Token', new_auth_token_path %>

app/views/auth_tokens/new.html.erb
<h1>New Auth Token</h1>

<%= render 'form', auth_token: @auth_token %>

<%= link_to 'Back', auth_tokens_path %>

app/views/auth_tokens/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <th>Token</th>
    <th>Label</th>
    <th>Groups</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @auth_token.token %></td>
      <td><%= @auth_token.label %></td>
      <td><%= @auth_token.groups.to_sentence %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_auth_token_path(@auth_token) %> |
<%= link_to 'Back', auth_tokens_path %>